language: python
sudo: false
dist: bionic  # 18.04
python:
  - 2.7
  - 3.7
  - pypy3
if: (type = push AND branch IN (master)) OR (type = pull_request)
cache: pip
install:
  - pip install poetry
  - poetry --version
  - poetry version
  - poetry install
script: poetry run py.test --cov=unihan_etl
after_success:
  - bash <(curl -s https://codecov.io/bash)
