__title__ = 'cihaidata-unihan'
__package_name__ = 'cihaidata_unihan'
__description__ = 'Tool to build UNIHAN dataset into datapackage / simple data format.'
__version__ = '0.4.2'
__author__ = 'Tony Narlock'
__email__ = 'cihai@git-pull.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2013-2017 Tony Narlock'
