__title__ = 'unihan-tabular'
__package_name__ = 'unihan_tabular'
__description__ = 'Download and export UNIHAN to Python, CSV, JSON and YAML'
__version__ = '0.5.0'
__author__ = 'Tony Narlock'
__email__ = 'cihai@git-pull.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2013-2017 Tony Narlock'
